### ISSUE TITLE
Usage of term blacklist

### ISSUE THREAD

**Issue by lighterlightbulb** [zyme-xd/discordtwt#3]
It is the year 2020 and you guys are using offensive terms such as "blacklist"? I am a Black male in Atlanta, Georgia and I could not be more appalled by this racist bigotry nonsense. I commend you to remove this disgusting word from the bot and from your vocabulary entirely. This is extremely offensive, and I will not stand for this racial discriminatory language used in the current day.

**Comment by zyme-xd** [comment]
you sir are indeed a comedian

**Comment by lighterlightbulb** [comment]
U r racist

**Comment by lighterlightbulb** [comment]
you sir are indeed a racist

**Comment by Madiwka4** [comment]
what is this lmao 🤣

**Comment by lighterlightbulb** [comment]
ok racist

**Comment by flickPF94** [comment]
...what

**Comment by Madiwka4** [comment]
Perhaps this thread should just be locked, @zyme-xd
